name: Tau
signal_files:
- /eos/home-d/drankin/GEPEnc/user.drankin.tgp_enc_ytt_feb14_EXT0/outputGEPNtuple.root
background_files:
- /eos/home-d/drankin/GEPEnc/user.drankin.tgp_enc_jz0_feb14_EXT0/outputGEPNtuple.root
- /eos/home-d/drankin/GEPEnc/user.drankin.tgp_enc_jz1_feb14_EXT0/outputGEPNtuple.root
- /eos/home-d/drankin/GEPEnc/user.drankin.tgp_enc_ytt_feb14_EXT0/outputGEPNtuple.root
background_weights:
- 76.66268004
- 3.656677112
- 0.0
reco_prefixes:
- AntiKt1GepCellsE6LSB40G4SIG2TowerAlgJets
- AntiKt1GepCellsE6LSB80G4SIG2TowerAlgJets
- AntiKt1GepCellsE6LSB40G4SIG4TowerAlgJets
- AntiKt1GepCellsE6LSB80G4SIG4TowerAlgJets
- L1_eTauRoISim
- L1_jFexSRJetRoI
- AntiKt1CaloTopoClusters422AlgJets
- AntiKt1OfflineCellsTowerAlgJets
- AntiKt3OfflineCellsTowerAlgJets
truth_prefix: truth_tau
truth_suffix: _vis
match_dict:
  pt_reco_names:
  - pt
  - pt
  - pt
  - pt
  - et
  - et
  - pt
  - pt
  - pt
reco_pt_min: 5.0
truth_pt_min: 10.0
pt_min: 2.0
reco_iso_dr: 0.4
truth_iso_dr: 0.4
nobjs:
- 1
- 2
selectors:
- name: null_selector
  label: ''
truth_pt_bins:
- 10.0
- 12.0
- 14.0
- 16.0
- 18.0
- 20.0
- 22.0
- 24.0
- 26.0
- 28.0
- 30.0
- 32.0
- 34.0
- 36.0
- 38.0
- 40.0
- 42.0
- 44.0
- 46.0
- 48.0
- 50.0
- 52.0
- 54.0
- 56.0
- 58.0
- 60.0
- 62.0
- 64.0
- 66.0
- 68.0
- 70.0
- 72.0
- 74.0
- 76.0
- 78.0
- 80.0
- 82.0
- 84.0
- 86.0
- 88.0
- 90.0
- 92.0
- 94.0
- 96.0
- 98.0
- 100.0
- 105.0
- 110.0
- 115.0
- 120.0
- 125.0
- 130.0
- 135.0
- 140.0
- 145.0
- 150.0
- 155.0
- 160.0
- 165.0
- 170.0
- 175.0
- 180.0
- 185.0
- 190.0
- 195.0
- 200.0
- 210.0
- 220.0
- 230.0
- 240.0
- 250.0
- 260.0
- 270.0
- 280.0
- 290.0
- 300.0
truth_eta_bins:
- -4.9
- -3.2
- -2.5
- -1.5
- -1.375
- -1.0
- 0.0
- 1.0
- 1.375
- 1.5
- 2.5
- 3.2
- 4.9
do_rho_sub: false
rates:
- 10.0
- 200.0
triggers:
- - 100.0
  - 150.0
- - 30.0
  - 40.0
extra_vars: []
tree: ntuple
dr_max: 0.2
